import {
  AirplaneTiltIcon,
  AppleLogoIcon,
  ArrowRightIcon,
  ArrowsHorizontalIcon,
  BabyIcon,
  BankIcon,
  BarbellIcon,
  BasketIcon,
  BedIcon,
  BeerSteinIcon,
  BellIcon,
  BooksIcon,
  BriefcaseIcon,
  CameraIcon,
  CameraRotateIcon,
  CaretDownIcon,
  CaretLeftIcon,
  CaretRightIcon,
  CaretUpIcon,
  CarIcon,
  CarSimpleIcon,
  CheckIcon,
  CoffeeIcon,
  CoinsIcon,
  CouchIcon,
  CreditCardIcon,
  DotsThreeIcon,
  DropIcon,
  EyeIcon,
  EyeSlashIcon,
  FirstAidIcon,
  ForkKnifeIcon,
  FrameCornersIcon,
  GameControllerIcon,
  GasPumpIcon,
  GearSixIcon,
  GiftIcon,
  GraduationCapIcon,
  HandHeartIcon,
  HandIcon,
  HeartIcon,
  HouseLineIcon,
  type IconProps as PhosphorProps,
  ImageIcon,
  LaptopIcon,
  LightningIcon,
  LightningSlashIcon,
  MagnifyingGlassIcon,
  MicrophoneIcon,
  MinusIcon,
  MopedIcon,
  MusicNotesIcon,
  PaletteIcon,
  PawPrintIcon,
  PencilSimpleIcon,
  PlayCircleIcon,
  PlusIcon,
  ReceiptIcon,
  RoadHorizonIcon,
  ScissorsIcon,
  ShieldCheckIcon,
  ShoppingBagIcon,
  ShoppingCartIcon,
  SparkleIcon,
  StarIcon,
  StopIcon,
  SunIcon,
  TargetIcon,
  TicketIcon,
  TrainIcon,
  TShirtIcon,
  WifiHighIcon,
  WrenchIcon,
  XIcon,
} from 'phosphor-react-native';

import { colors } from '@/shared/lib/theme';

// Icons are referenced by their Phosphor kebab-case name so category icons can
// be stored as plain text in the database.
const registry = {
  'airplane-tilt': AirplaneTiltIcon,
  'apple-logo': AppleLogoIcon,
  'arrow-right': ArrowRightIcon,
  'arrows-horizontal': ArrowsHorizontalIcon,
  baby: BabyIcon,
  bank: BankIcon,
  barbell: BarbellIcon,
  basket: BasketIcon,
  bed: BedIcon,
  'beer-stein': BeerSteinIcon,
  bell: BellIcon,
  books: BooksIcon,
  briefcase: BriefcaseIcon,
  camera: CameraIcon,
  'camera-rotate': CameraRotateIcon,
  car: CarIcon,
  'car-simple': CarSimpleIcon,
  'caret-down': CaretDownIcon,
  'caret-left': CaretLeftIcon,
  'caret-right': CaretRightIcon,
  'caret-up': CaretUpIcon,
  check: CheckIcon,
  coffee: CoffeeIcon,
  coins: CoinsIcon,
  couch: CouchIcon,
  'credit-card': CreditCardIcon,
  'dots-three': DotsThreeIcon,
  drop: DropIcon,
  eye: EyeIcon,
  'eye-slash': EyeSlashIcon,
  'first-aid': FirstAidIcon,
  'fork-knife': ForkKnifeIcon,
  'frame-corners': FrameCornersIcon,
  'game-controller': GameControllerIcon,
  'gas-pump': GasPumpIcon,
  'gear-six': GearSixIcon,
  gift: GiftIcon,
  'graduation-cap': GraduationCapIcon,
  hand: HandIcon,
  'hand-heart': HandHeartIcon,
  heart: HeartIcon,
  'house-line': HouseLineIcon,
  image: ImageIcon,
  laptop: LaptopIcon,
  lightning: LightningIcon,
  'lightning-slash': LightningSlashIcon,
  'magnifying-glass': MagnifyingGlassIcon,
  microphone: MicrophoneIcon,
  minus: MinusIcon,
  moped: MopedIcon,
  'music-notes': MusicNotesIcon,
  palette: PaletteIcon,
  'paw-print': PawPrintIcon,
  'pencil-simple': PencilSimpleIcon,
  'play-circle': PlayCircleIcon,
  plus: PlusIcon,
  receipt: ReceiptIcon,
  'road-horizon': RoadHorizonIcon,
  scissors: ScissorsIcon,
  'shield-check': ShieldCheckIcon,
  'shopping-bag': ShoppingBagIcon,
  'shopping-cart': ShoppingCartIcon,
  sparkle: SparkleIcon,
  star: StarIcon,
  stop: StopIcon,
  sun: SunIcon,
  't-shirt': TShirtIcon,
  target: TargetIcon,
  ticket: TicketIcon,
  train: TrainIcon,
  'wifi-high': WifiHighIcon,
  wrench: WrenchIcon,
  x: XIcon,
} as const;

export type IconName = keyof typeof registry;

function isIconName(value: string): value is IconName {
  return value in registry;
}

export interface IconProps extends Omit<PhosphorProps, 'weight'> {
  name: IconName | string;
  weight?: 'regular' | 'bold' | 'fill';
}

export function Icon({
  name,
  weight = 'bold',
  size = 18,
  color = colors.inkSoft,
  ...props
}: IconProps) {
  const Component = isIconName(name) ? registry[name] : SparkleIcon;
  return <Component weight={weight} size={size} color={color} {...props} />;
}
